# -*- coding: utf-8 -*-
"""Email Validator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x1E4Fc2XiRd7RBLDRFawcguaeV_skVH9
"""

import re
 def is_valid_email(email):
    pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    if re.match(pattern, email):
        return True
    else:
       return False
 def main():
    email = input("Enter an email address: ")
    if is_valid_email(email):
        print("Valid email address.")
    else:
        print("Invalid email address.")
 if __name__ == "__main__":
  main()